### ISSUE TITLE
issue when running npm install

### ISSUE THREAD

**Issue by npatel2012** [snoussi/qlb-loan-application-ui#2]
**npm install** command on Linux (Version: Red Hat Enterprise Linux Workstation release 7.3 (Maipo)) gives me the following error:

_**node: error while loading shared libraries: libhttp_parser.so.2: cannot open shared object file: No such file or directory**_

**Comment by snoussi** [comment]
did you try this: [Problem installing in Linux #1](https://github.com/snoussi/qlb-loan-application-ui/issues/1)

**Comment by npatel2012** [comment]
same error... issue is seen when running "npm install" command... Issue #1 is an error which is thrown later on in the logs

**Comment by npatel2012** [comment]
got past this error by running following command:

"yum install http-parser"
